export const SET_DATA = 'SET_DATA';

export const GET_ASYNC_DATA_REQUEST = 'GET_ASYNC_DATA_REQUEST';
export const GET_ASYNC_DATA_SUCCESS = 'GET_ASYNC_DATA_SUCCESS';

export const PING_BACKEND_REQUEST = 'PING_BACKEND_REQUEST';
export const PING_BACKEND_SUCCESS = 'PING_BACKEND_SUCCESS';
export const PING_BACKEND_FAIL = 'PING_BACKEND_FAIL';

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL';
